Fix user profile overwriting issue
OpenHospitalityNetwork/sleepy-bike-solid pull request #88
Opened 2024-03-02 23:16 UTC by mariha

2024-03-04 06:50 UTC, mrkvon requested changes
:+1: This should indeed fix the issue. Here's a reference to Solid specification: https://solidproject.org/TR/protocol#conditional-update (may be worth including)

It looks like the tests are failing. I looked into it and it seems that we shouldn't use the `If-None-Match: *` header when we use `POST` method. With `POST` a new resource within given existing container is created (and that header actually causes error). Only with `PUT` or `PATCH`, the resource may actually be overwritten.

@mariha do you prefer to fix it yourself? Or may i push a fix?

2024-03-12 20:27 UTC, mariha commented
You are very welcome to push the fix, @mrkvon!

2024-03-12 22:37 UTC, mrkvon commented
Ok, pushed the fix, hopefully the tests will pass... then we can merge :)

2024-03-12 22:57 UTC, mrkvon approved these changes
The tests pass. Great to have this overwrite safety!

2024-03-12 23:01 UTC, merged

2024-03-14 11:27 UTC, mariha commented
I'm surprised that you didn't add me as a reviewer after we changed ownership of the changes, @mrkvon. 

We didn't discuss changes in this process, afair? I know that you left a proposition to make such a change [in the meeting notes](https://pad.kanthaus.online/ohn) but I haven't answer anything and [I did address the issue of piling PRs](https://github.com/OpenHospitalityNetwork/sleepy.bike/pull/81) you raised (plural was an exaggeration of you):
> * [michal] Process
>    * The requirement for code reviews on sleepy.bike repo makes the progress slower and more frustrating. Currently I have piling PRs depending on each other. I think it doesn't make sense to require code reviews as long as there are 1-2 authors. Can we either pause it (for me :wink: or for owners) until there are more people, or give a limited time for a review, after which merge without review is allowed?

The process is our common ownership, and changes to it are subject to our common decisions, not yours.

2024-03-14 14:47 UTC, mrkvon commented
Sorry, my bad. I didn't realize it would be meaningful for you to do another round of approvals. It has nothing to do with my proposal.